if: tag IS blank

language: go

go:
  - "1.14"
branches:
  only:
    - dev

install: true

env:
  - GO111MODULE=on

jobs:
  include:
    - name: linux
      os: linux
      dist: xenial
      sudo: required

      before_install:
        - git clone https://$GITHUB_TOKEN@github.com/appbaseio-confidential/arc-noss

      script:
        - cd arc-noss
        - go mod download
        - make clean && make

      before_deploy:
        - mkdir -p go/pkg/mod/github.com/appbaseio/
        - sudo mv $GOPATH/pkg/mod/github.com/appbaseio/* go/pkg/mod/github.com/appbaseio/
        - zip -r arc-linux.zip build go sample
        - export TRAVIS_TAG="preview"

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file: arc-linux.zip
        draft: true
        overwrite: true
        on:
          all_branches: true
