version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    container_name: elasticsearch
    networks:
      - arc
    environment:
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  arc:
    build: ./
    container_name: arc
    networks:
      - arc
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
  streams:
    image: appbaseio/streams:latest
    container_name: streams
    networks:
      - arc
    environment:
      - ES_NODES=arc:8000
      - SSL_OFF=yes
      - AUTH_OFF=yes
      - DNS_SERVER=127.0.0.11
      - DOMAIN_NAME=localhost
      - ARC_USER=foo
      - ARC_PASS=bar
    ports:
      - 80:80
      - 443:443
      - 5678:5678
    depends_on:
      - arc

networks:
  arc:
    driver: bridge
